# Generated by Django 6.0.3 on 2026-05-09 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano_banana', '0001_add_platform_captions'),
        ('workspace', '0003_repair_legacy_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NanoGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('create_post', 'Create post'), ('regenerate_image', 'Regenerate image'), ('edit_generated_image', 'Edit generated image')], max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nano_banana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='nano_banana.nanobananaimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nano_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nano_generation_jobs', to='workspace.workspace')),
            ],
            options={
                'db_table': 'nano_generation_job',
                'indexes': [models.Index(fields=['user', 'workspace', 'status'], name='nano_genera_user_id_a89193_idx'), models.Index(fields=['job_type', 'created_at'], name='nano_genera_job_typ_9eced8_idx')],
            },
        ),
    ]
