# Generated by Django 6.0.3 on 2026-05-10 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0003_repair_legacy_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('id_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_token', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_linkedin_token', to='workspace.workspace')),
            ],
            options={
                'db_table': 'linkedin_Token',
            },
        ),
        migrations.CreateModel(
            name='LinkedinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=500)),
                ('picture_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_linkedin_profile', to='workspace.workspace')),
            ],
            options={
                'db_table': 'linkedin_user',
            },
        ),
        migrations.CreateModel(
            name='LinkedinPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=100)),
                ('organization_urn', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('vanity_name', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('role', models.CharField(max_length=100)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_pages', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_pages', to='workspace.workspace')),
            ],
            options={
                'db_table': 'linkedin_page',
                'unique_together': {('workspace', 'organization_id')},
            },
        ),
    ]
