# Generated by Django 6.0.3 on 2026-05-03 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0003_repair_legacy_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('monthly_marketing_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('business_category', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(max_length=1000)),
                ('tone', models.CharField(blank=True, max_length=255)),
                ('services', models.JSONField(blank=True, default=list)),
                ('audience', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('editable_markdown', models.TextField(blank=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BrandSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visual_style', models.CharField(blank=True, max_length=32)),
                ('recommended_visual_style', models.JSONField(blank=True, default=dict)),
                ('font', models.JSONField(blank=True, default=dict)),
                ('tone', models.CharField(blank=True, max_length=255)),
                ('image_style', models.TextField(blank=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('logos', models.JSONField(blank=True, default=list)),
                ('brand_context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_settings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_settings', to='workspace.workspace')),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_settings', to='content_engine.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('posts_per_week', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('brand_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_plans', to='content_engine.brandsetting')),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to='content_engine.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BlogEmailPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_plan', models.JSONField(blank=True, default=dict)),
                ('email_plan', models.JSONField(blank=True, default=dict)),
                ('content_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_email_plan', to='content_engine.contentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='content_engine.contentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_generation_jobs', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
                ('asset_type', models.CharField(default='image', max_length=32)),
                ('source', models.CharField(default='generated', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_media_assets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_media_assets', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=1)),
                ('title', models.TextField()),
                ('kind', models.CharField(default='social', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content_engine.contentplan')),
            ],
            options={
                'ordering': ['week_number', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_outputs', models.JSONField(blank=True, default=dict)),
                ('image_prompt', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_posts', to='content_engine.contentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_generated_posts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_generated_posts', to='workspace.workspace')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_posts', to='content_engine.generationjob')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_posts', to='content_engine.mediaasset')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_posts', to='content_engine.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['user', 'workspace'], name='content_eng_user_id_2ccfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['website_url'], name='content_eng_website_0118fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessprofile',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='unique_business_profile_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='brandsetting',
            index=models.Index(fields=['user', 'workspace'], name='content_eng_user_id_ef713b_idx'),
        ),
        migrations.AddConstraint(
            model_name='brandsetting',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='unique_brand_setting_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='contentplan',
            index=models.Index(fields=['user', 'workspace', 'status'], name='content_eng_user_id_aca7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['user', 'workspace', 'status'], name='content_eng_user_id_e4a2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['user', 'workspace', 'asset_type'], name='content_eng_user_id_09b692_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['content_plan', 'week_number', 'kind'], name='content_eng_content_a6180e_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedpost',
            index=models.Index(fields=['user', 'workspace', 'status', 'scheduled_for'], name='content_eng_user_id_b73218_idx'),
        ),
    ]
