# Generated by Django 6.0.3 on 2026-05-04 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0002_contentplan_blog_email_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('theme', models.TextField(blank=True)),
                ('funnel_goal', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('generated', 'Generated')], default='draft', max_length=32)),
                ('item_plan', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_weeks', to='content_engine.contentplan')),
            ],
            options={
                'ordering': ['week_number', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='campaign_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='content_engine.campaignweek'),
        ),
        migrations.AddIndex(
            model_name='campaignweek',
            index=models.Index(fields=['content_plan', 'week_number', 'status'], name='content_eng_content_2d398b_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignweek',
            constraint=models.UniqueConstraint(fields=('content_plan', 'week_number'), name='unique_campaign_week_per_plan'),
        ),
    ]
