# Generated by Django 6.0.3 on 2026-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0003_campaignweek_generationjob_campaign_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplan',
            name='blog_posts_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='emails_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
