# Generated by Django 6.0.3 on 2026-05-05 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0004_alter_contentplan_blog_posts_per_week_and_more'),
        ('workspace', '0003_repair_legacy_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMatrixEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('source_type', models.CharField(choices=[('my_website', 'My Website'), ('competitor', 'Competitor Website')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_matrix_entries', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_matrix_entries', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('pricing_model', models.TextField(blank=True)),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('differentiators', models.JSONField(blank=True, default=list)),
                ('swot', models.JSONField(blank=True, default=dict)),
                ('objection_handling', models.JSONField(blank=True, default=dict)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analyses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analyses', to='workspace.workspace')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_analyses', to='content_engine.sourcematrixentry')),
            ],
        ),
        migrations.CreateModel(
            name='AudienceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('age_range', models.CharField(blank=True, max_length=128)),
                ('location', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('frustrations', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('behaviors', models.JSONField(blank=True, default=list)),
                ('buying_patterns', models.JSONField(blank=True, default=list)),
                ('awareness_level', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_profiles', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_profiles', to='workspace.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'workspace', 'name'], name='content_eng_user_id_4fafcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrandManualData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processes', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('pricing', models.TextField(blank=True)),
                ('onboarding', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_manual_data', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_manual_data', to='workspace.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'workspace'], name='content_eng_user_id_024560_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelVoiceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=64)),
                ('tone', models.TextField(blank=True)),
                ('emotion', models.TextField(blank=True)),
                ('character', models.TextField(blank=True)),
                ('syntax', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_voice_configs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_voice_configs', to='workspace.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'workspace', 'platform'], name='content_eng_user_id_45764d_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'platform'), name='unique_channel_voice_per_workspace')],
            },
        ),
        migrations.AddIndex(
            model_name='sourcematrixentry',
            index=models.Index(fields=['user', 'workspace', 'source_type', 'status'], name='content_eng_user_id_406078_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcematrixentry',
            index=models.Index(fields=['workspace', 'url'], name='content_eng_workspa_a73737_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcematrixentry',
            constraint=models.UniqueConstraint(fields=('workspace', 'url', 'source_type'), name='unique_source_per_workspace_type'),
        ),
        migrations.AddIndex(
            model_name='competitoranalysis',
            index=models.Index(fields=['user', 'workspace'], name='content_eng_user_id_681a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalysis',
            index=models.Index(fields=['workspace', 'website_url'], name='content_eng_workspa_824306_idx'),
        ),
    ]
