# Generated by Codex on 2026-05-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0005_sourcematrixentry_competitoranalysis_audienceprofile_and_more'),
        ('workspace', '0003_repair_legacy_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceIntelligenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('brand_enrichment', 'Brand enrichment'), ('competitor_discovery', 'Competitor discovery')], max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_jobs', to='content_engine.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_intelligence_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_jobs', to='workspace.workspace')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'workspace', 'status'], name='content_eng_user_id_154b80_idx'),
                    models.Index(fields=['workspace', 'job_type', 'status'], name='content_eng_workspa_b6f743_idx'),
                ],
            },
        ),
    ]
