from django.urls import path

from .views import (
    BlogEmailPlanView,
    BrandSettingsView,
    BusinessProfileView,
    AudienceProfileDetailView,
    AudienceProfilesView,
    CampaignPlanCreateBatchView,
    CampaignPlanReorderView,
    CampaignPlanView,
    CampaignPromptRegenerateView,
    CampaignWeekApproveView,
    CampaignWeekGenerateView,
    CampaignWeekRegenerateView,
    CampaignWeekView,
    ChannelVoiceView,
    CompetitorDetailView,
    CompetitorReanalyzeView,
    CompetitorsView,
    ContentPlanView,
    GenerateFirstWeekView,
    ManualDataView,
    OnboardingStateView,
    RecommendedVisualStylesView,
    SourceMatrixAnalyzeView,
    SourceMatrixView,
    TopicsView,
)


urlpatterns = [
    path('business-profile/', BusinessProfileView.as_view(), name='content_business_profile'),
    path('onboarding-state/', OnboardingStateView.as_view(), name='content_onboarding_state'),
    path('brand-settings/', BrandSettingsView.as_view(), name='content_brand_settings'),
    path('source-matrix/', SourceMatrixView.as_view(), name='content_source_matrix'),
    path('source-matrix/analyze/', SourceMatrixAnalyzeView.as_view(), name='content_source_matrix_analyze'),
    path('competitors/', CompetitorsView.as_view(), name='content_competitors'),
    path('competitors/<uuid:competitor_id>/', CompetitorDetailView.as_view(), name='content_competitor_detail'),
    path('competitors/<uuid:competitor_id>/reanalyze/', CompetitorReanalyzeView.as_view(), name='content_competitor_reanalyze'),
    path('channel-voice/', ChannelVoiceView.as_view(), name='content_channel_voice'),
    path('audience-profiles/', AudienceProfilesView.as_view(), name='content_audience_profiles'),
    path('audience-profiles/<uuid:audience_id>/', AudienceProfileDetailView.as_view(), name='content_audience_profile_detail'),
    path('manual-data/', ManualDataView.as_view(), name='content_manual_data'),
    path('recommended-visual-styles/', RecommendedVisualStylesView.as_view(), name='content_recommended_visual_styles'),
    path('content-plan/', ContentPlanView.as_view(), name='content_plan'),
    path('topics/', TopicsView.as_view(), name='content_topics'),
    path('blog-email-plan/', BlogEmailPlanView.as_view(), name='content_blog_email_plan'),
    path('generate-first-week/', GenerateFirstWeekView.as_view(), name='content_generate_first_week'),
    path('campaign-plan/', CampaignPlanView.as_view(), name='content_campaign_plan'),
    path('campaign-plan/create-batch/', CampaignPlanCreateBatchView.as_view(), name='content_campaign_plan_create_batch'),
    path('campaign-plan/reorder/', CampaignPlanReorderView.as_view(), name='content_campaign_plan_reorder'),
    path('campaign-plan/<uuid:week_id>/', CampaignWeekView.as_view(), name='content_campaign_week'),
    path('campaign-plan/<uuid:week_id>/approve/', CampaignWeekApproveView.as_view(), name='content_campaign_week_approve'),
    path('campaign-plan/<uuid:week_id>/generate/', CampaignWeekGenerateView.as_view(), name='content_campaign_week_generate'),
    path('campaign-plan/<uuid:week_id>/regenerate/', CampaignWeekRegenerateView.as_view(), name='content_campaign_week_regenerate'),
    path('campaign-plan/<uuid:week_id>/prompt-regenerate/', CampaignPromptRegenerateView.as_view(), name='content_campaign_prompt_regenerate'),
]
