export const VISUAL_STYLE_OPTIONS = [
  {
    id: "ultra_realistic",
    name: "Ultra Realistic",
    label: "Ultra Realistic",
    recommended: true,
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&q=85&auto=format&fit=crop",
    image_url: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&q=85&auto=format&fit=crop",
    imagePosition: "center",
    description: "Real humans, real places, natural light, premium commercial photography.",
    prompt: "ultra-realistic commercial photography with real humans or real places, natural skin texture, authentic environments, premium lighting, no cartoon or illustration",
    subject: "Real people",
    output: "Photo",
    tone: "Premium",
  },
  {
    id: "infographic",
    name: "Infographic",
    label: "Infographic",
    recommended: false,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=85&auto=format&fit=crop",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=85&auto=format&fit=crop",
    imagePosition: "center",
    description: "Data-led layouts, diagrams, icons, comparison blocks, readable structure.",
    prompt: "modern branded infographic style with clean layout, data visualization, icons, diagrams, structured composition, minimal text only when necessary",
    subject: "Data",
    output: "Graphic",
    tone: "Clear",
  },
  {
    id: "cartoon_animated",
    name: "Cartoon / Animated",
    label: "Cartoon / Animated",
    recommended: false,
    image: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1200&q=85&auto=format&fit=crop",
    image_url: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1200&q=85&auto=format&fit=crop",
    imagePosition: "center",
    description: "Illustrated characters, animated scenes, playful brand storytelling.",
    prompt: "polished cartoon animation style with expressive illustrated characters, playful shapes, clean brand colors, social-media-ready composition",
    subject: "Characters",
    output: "Illustration",
    tone: "Playful",
  },
  {
    id: "product_studio",
    name: "Product Studio",
    label: "Product Studio",
    recommended: false,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=1200&q=85&auto=format&fit=crop",
    image_url: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=1200&q=85&auto=format&fit=crop",
    imagePosition: "center",
    description: "Sharp product or service visuals, studio lighting, clean premium backgrounds.",
    prompt: "premium product studio photography, sharp focus, clean background, controlled lighting, polished product or service hero composition",
    subject: "Product",
    output: "Studio",
    tone: "Polished",
  },
  {
    id: "editorial_lifestyle",
    name: "Editorial Lifestyle",
    label: "Editorial Lifestyle",
    recommended: false,
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=85&auto=format&fit=crop",
    image_url: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=85&auto=format&fit=crop",
    imagePosition: "center",
    description: "Human lifestyle moments with brand context, workplace scenes, editorial mood.",
    prompt: "editorial lifestyle photography with real people, workplace or customer context, cinematic but natural lighting, brand-specific story moment",
    subject: "Lifestyle",
    output: "Editorial",
    tone: "Warm",
  },
];
