# Generated by Django 6.0.3 on 2026-05-09 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nano_banana', '0002_nanogenerationjob'),
        ('workspace', '0003_repair_legacy_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_image_url', to='workspace.workspace')),
            ],
            options={
                'db_table': 'image_url',
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('approval', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved'), ('ready', 'Ready for Approval'), ('posted', 'Posted')], default='not_approved', max_length=20)),
                ('nano_banana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nano_banana.nanobananaimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_post', to='workspace.workspace')),
            ],
            options={
                'db_table': 'scheduled_post',
            },
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_images', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_upload_images', to='workspace.workspace')),
            ],
            options={
                'db_table': 'upload_images',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('approval_toggle', models.BooleanField(default=True)),
                ('brand_voice', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_user_profile', to='workspace.workspace')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
